export const USER_REGISTRATION_PENDING = "USER_REGISTRATION_PENDING";
export const USER_REGISTRATION_REJECT = "USER_REGISTRATION_REJECT";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";

export const USER_LOGIN_PENDING = "USER_LOGIN_PENDING";
export const USER_LOGIN_REJECT = "USER_LOGIN_REJECT";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const DATA_SHOW_PENDING = "DATA_SHOW_PENDING";
export const DATA_SHOW_REJECT = "DATA_SHOW_REJECT";
export const DATA_SHOW_SUCCESS = "DATA_SHOW_SUCCESS";

export const CONTACT_FORM_PENDING = "CONTACT_FORM_PENDING";
export const CONTACT_FORM_REJECT = "CONTACT_FORM_REJECT";
export const CONTACT_FORM_SUCCESS = "CONTACT_FORM_SUCCESS";

export const PAYMENT_PENDING = "PAYMENT_PENDING";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";

export const ADD_TO_CART_FUN_RUNER = "ADD_TO_CART_FUN_RUNER";

export const NAVBAR_INPUT_PART_VALUE = "NAVBAR_INPUT_PART_VALUE";

export const CART_PAYMENT_CART_PART = "CART_PAYMENT_CART_PART";
